# Generated by Django 3.0.5 on 2020-04-19 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='file_storage',
        ),
    ]
