# Generated by Django 3.0.5 on 2020-09-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='myfile',
            new_name='docfile',
        ),
    ]
