# Generated by Django 3.0.5 on 2020-10-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='username',
            field=models.CharField(default='User_name', max_length=255),
        ),
    ]
